import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:printing/printing.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/case_models.dart';

class PdfShareScreen extends StatelessWidget {
  final CaseRecord caseRecord;
  const PdfShareScreen({super.key, required this.caseRecord});

  Future<Uint8List> _buildPdf() async {
    final pdf = pw.Document();
    pdf.addPage(
      pw.MultiPage(
        build:
            (context) => [
              pw.Header(
                level: 0,
                child: pw.Text(
                  'Case Summary',
                  style: pw.TextStyle(
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),
              pw.SizedBox(height: 8),
              _kv('Title', caseRecord.title),
              _kv('Category', caseRecord.category),
              _kv(
                'Description',
                caseRecord.description.isEmpty ? '—' : caseRecord.description,
              ),
              _kv('Notes', caseRecord.notes.isEmpty ? '—' : caseRecord.notes),
              pw.SizedBox(height: 12),
              pw.Text(
                'Deadlines',
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              if (caseRecord.deadlines.isEmpty) pw.Text('No deadlines added.'),
              ...caseRecord.deadlines.map(
                (d) => pw.Bullet(
                  text:
                      '${d.title} — due ${d.dueDate.toLocal()} (${d.completed ? 'completed' : 'open'})',
                ),
              ),
              pw.SizedBox(height: 12),
              pw.Text(
                'Attachments',
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              if (caseRecord.attachments.isEmpty) pw.Text('No attachments.'),
              ...caseRecord.attachments.map(
                (a) => pw.Bullet(text: '${a.name} — ${a.path}'),
              ),
              pw.SizedBox(height: 24),
              pw.Paragraph(
                text:
                    'Generated by AI Pocket Lawyer. This summary is for informational purposes only and is not legal advice.',
              ),
            ],
      ),
    );
    return pdf.save();
  }

  pw.Widget _kv(String k, String v) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(k, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 2),
        pw.Text(v),
        pw.SizedBox(height: 8),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Share PDF')),
      body: PdfPreview(
        build: (_) => _buildPdf(),
        canChangePageFormat: true,
        canChangeOrientation: true,
        allowSharing: true,
        allowPrinting: true,
      ),
    );
  }
}
